version: "3.8"

services:
  db:
    image: postgres:15
    container_name: blabberit_db
    restart: always
    environment:
      POSTGRES_USER: blabberuser
      POSTGRES_PASSWORD: blabberpass
      POSTGRES_DB: blabberit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_test:
    image:

volumes:
  pgdata:
