# .github/workflows/ci.yml
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: blabberuser
          POSTGRES_PASSWORD: blabberpass
          POSTGRES_DB: blabberit_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U blabberuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run tests
        env:
          POSTGRES_DSN: host=localhost user=blabberuser password=blabberpass dbname=blabberit_test port=5432 sslmode=disable TimeZone=UTC
        run: go test ./...
